### ISSUE TITLE
IPython nb error

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#122]
Any thoughts on this

```
Stevens-MacBook-Air-2:pubathon-2015 sr320$ ipython notebook
Traceback (most recent call last):
  File "/Users/sr320/anaconda/bin/ipython", line 6, in <module>
    sys.exit(start_ipython())
  File "/Users/sr320/anaconda/lib/python2.7/site-packages/IPython/__init__.py", line 120, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/Users/sr320/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 573, in launch_instance
    app.initialize(argv)
  File "<string>", line 2, in initialize
  File "/Users/sr320/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/sr320/anaconda/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 321, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<string>", line 2, in initialize
  File "/Users/sr320/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/sr320/anaconda/lib/python2.7/site-packages/IPython/core/application.py", line 369, in initialize
    self.parse_command_line(argv)
  File "/Users/sr320/anaconda/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 316, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<string>", line 2, in parse_command_line
  File "/Users/sr320/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/sr320/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 471, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "<string>", line 2, in initialize_subcommand
  File "/Users/sr320/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/sr320/anaconda/lib/python2.7/site-packages/IPython/config/application.py", line 402, in initialize_subcommand
    subapp = import_item(subapp)
  File "/Users/sr320/anaconda/lib/python2.7/site-packages/IPython/utils/importstring.py", line 42, in import_item
    module = __import__(package, fromlist=[obj])
  File "/Users/sr320/anaconda/lib/python2.7/site-packages/IPython/html/notebookapp.py", line 30, in <module>
    check_for_zmq('13', 'IPython.html')
  File "/Users/sr320/anaconda/lib/python2.7/site-packages/IPython/utils/zmqrelated.py", line 18, in check_for_zmq
    required_by, minimum_version, pyzmq_version))
ImportError: IPython.html requires pyzmq >= 13, but you have 2.2.0.1
Stevens-MacBook-Air-2:pubathon-2015 sr320$ conda update conda
Fetching package metadata: ....
# All requested packages already installed.
# packages in environment at /Users/sr320/anaconda:
#
conda                     3.14.0                   py27_0  
Stevens-MacBook-Air-2:pubathon-2015 sr320$ conda update ipython
Fetching package metadata: ....
# All requested packages already installed.
# packages in environment at /Users/sr320/anaconda:
#
ipython                   3.2.0                    py27_0  
```

**Comment by kubu4** [comment]
Looks like you'll have to uninstall, and then reinstall, the pyzmq module. Everything I've read says to use pip (a package manager), but I don't think Macs have that by default. You could try to uninstall the package with Anaconda, but I don't know what the specific command would be.

**Comment by sr320** [comment]
thanks! ended up uninstalling and reinstalling anaconda, just seemed weird anaconda update would not remedy.
