### ISSUE TITLE
Abacus java error

### ISSUE THREAD

**Issue by sr320** [sr320/LabDocs#487]
In running Abacus-

Please see full explanation: https://sr320.github.io/Abacus-Failure/

I error out with 

```
 Adding data from X20161205_SAMPLE_8A

Creating NSAF values table (protein-centric)
  NSAF_FACTOR = 10^5 = 100000.0
java.sql.SQLSyntaxErrorException: user lacks privilege or object not found: NAN
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCStatement.fetchResult(Unknown Source)
	at org.hsqldb.jdbc.JDBCStatement.executeUpdate(Unknown Source)
	at abacus.hyperSQLObject.getNSAF_values_prot(hyperSQLObject.java:2961)
	at abacus.abacus.main(abacus.java:221)
	at mainFunction.mainFunction.main(mainFunction.java:49)
Caused by: org.hsqldb.HsqlException: user lacks privilege or object not found: NAN
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.ExpressionColumn.checkColumnsResolved(Unknown Source)
	at org.hsqldb.ParserDML.resolveUpdateExpressions(Unknown Source)
	at org.hsqldb.ParserDML.compileUpdateStatement(Unknown Source)
	at org.hsqldb.ParserCommand.compilePart(Unknown Source)
	at org.hsqldb.ParserCommand.compileStatements(Unknown Source)
	at org.hsqldb.Session.executeDirectStatement(Unknown Source)
	at org.hsqldb.Session.execute(Unknown Source)
	... 5 more

```

This has not happened before, the only difference (that I know of) is that I changed the Abacus parameter file.

**Comment by kubu4** [comment]
You don't have execute permissions on the params file (use ls -l to view permissions). Maybe that's the issue?

**Comment by kubu4** [comment]
To clarify, I'm guessing that's the issue, due to this part of the error message:

```java.sql.SQLSyntaxErrorException: user lacks privilege```

**Comment by sr320** [comment]
So maybe I should do a chmod 777 on the file?

**Comment by sr320** [comment]
I will check first as you indicate-

**Comment by seanb80** [comment]
The Protein Fasta FIle is mislabeled in the params file. 

Changing it to `Cg-Giga_cont_AA.fa` from `Cg_Giga_cont_AA.fa` seems to work. 

![emufafile](https://cloud.githubusercontent.com/assets/10619258/22985035/162a38f4-f35c-11e6-8526-3a26930eff90.png)

![abparam](https://cloud.githubusercontent.com/assets/10619258/22985042/196b3658-f35c-11e6-8807-aa24e85aa841.png)

**Comment by kubu4** [comment]
Damn! Nice catch, @seanb80 ! What lead you to identifying that?

@sr320 you can use: 

```chmod +x <file>```

**Comment by seanb80** [comment]
I was copying files over to my directory in Emu via cut and paste, and it didn't find that file!

**Comment by kubu4** [comment]
Wow!

**Comment by sr320** [comment]
Changed the Abacus param file...


but still spitting out errror

```
ding data from X20161205_SAMPLE_51
  Adding data from X20161205_SAMPLE_51A
  Adding data from X20161205_SAMPLE_52
  Adding data from X20161205_SAMPLE_52A
  Adding data from X20161205_SAMPLE_56
  Adding data from X20161205_SAMPLE_56A
  Adding data from X20161205_SAMPLE_8
  Adding data from X20161205_SAMPLE_8A

Creating NSAF values table (protein-centric)
  NSAF_FACTOR = 10^5 = 100000.0
java.sql.SQLSyntaxErrorException: user lacks privilege or object not found: NAN
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCStatement.fetchResult(Unknown Source)
	at org.hsqldb.jdbc.JDBCStatement.executeUpdate(Unknown Source)
	at abacus.hyperSQLObject.getNSAF_values_prot(hyperSQLObject.java:2961)
	at abacus.abacus.main(abacus.java:221)
	at mainFunction.mainFunction.main(mainFunction.java:49)
Caused by: org.hsqldb.HsqlException: user lacks privilege or object not found: NAN
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.ExpressionColumn.checkColumnsResolved(Unknown Source)
	at org.hsqldb.ParserDML.resolveUpdateExpressions(Unknown Source)
	at org.hsqldb.ParserDML.compileUpdateStatement(Unknown Source)
	at org.hsqldb.ParserCommand.compilePart(Unknown Source)
	at org.hsqldb.ParserCommand.compileStatements(Unknown Source)
	at org.hsqldb.Session.executeDirectStatement(Unknown Source)
	at org.hsqldb.Session.execute(Unknown Source)
	... 5 more
```

**Comment by sr320** [comment]
@kubu4 

```
ls -l A*
-rw-rw-r-- 1 steven steven 2498 Feb 15 09:31 Abacus-01.param
````

same as one that worked

```
-rw-rw-r-- 1 steven steven    2482 Feb 12 15:26 Abacus.param
```

**Comment by kubu4** [comment]
What happens when you change permissions?

**Comment by sr320** [comment]
I have a feeling Sean was on to something, but that I have to rerun the
pipeline so I have started comet and will see.
The reason I feel this way is if you look at stdout after the param file
change. It still seems to be using a different library -likely an artifact
of comet / TPP..

**Comment by seanb80** [comment]
I copied over all of the files from `bioinfo/021417` and Abacus ran fine to completion, without any errors.

It seems to be crashing on the step where it writes ABACUS_output.tsv.

It looks like our directory permissions are the same

mine (StevenAbacus):

![mydirperm](https://cloud.githubusercontent.com/assets/10619258/22999160/f5425120-f38e-11e6-8b9a-ee44445a4466.png)

and Stevens:

![stevendirperm](https://cloud.githubusercontent.com/assets/10619258/22999171/ff249a68-f38e-11e6-9f11-f9ade2b71c73.png)

Not sure what's going on... Maybe try running the java instance as sudo, to see if you can force the ability to write it, or maybe try writing the output file to another directory?

**Comment by sr320** [comment]
Yes- I tried sudo- no luck.
To clarify- you ran abacus and got the abacus output?

**Comment by seanb80** [comment]
Oh! There are two instances of the Cg-Giga_cont_AA.fa in the param file.

First:
`
# Name to give the database
dbName=Cg-Giga_cont_AA.fa
`

and lower, which still shows the _ as opposed to the -:
`
# The path the the FASTA formatted file used for the original protein search
# Relative paths are allowed
fasta=Cg_Giga_cont_AA.fa
`
Maybe thats it? Otherwise, the only thing I changed were the directories files were located/output to.

My param file:

[Abacus-01.txt](https://github.com/sr320/LabDocs/files/778610/Abacus-01.txt)

**Comment by sr320** [comment]
Another good catch..

That made the error message smaller. I have mangled so many files (and
doing this on an iPad)
I am going to take a pause. And start a fresh from the beginning later to
see if I can get to the tsv.

**Comment by sr320** [comment]
I am going to close this, as I am 99% sure this is just my own syntax error.....
